
version: 2

sources:
  - name: raw_data
    database: example_db
    schema: public
    tables:
      - name: raw_orders
        columns:
          - name: order_id
          - name: customer_id
          - name: product_id
          - name: order_date
          - name: amount

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: base_sql_model
    description: "Base SQL model with product data"
    columns:
      - name: id
        description: "Product ID"
      - name: product_name
        description: "Product name"
      - name: price
        description: "Product price"
      - name: quantity
        description: "Product quantity"

  - name: base_python_model
    description: "Base Python model with customer data"
    columns:
      - name: customer_id
        description: "Customer ID"
      - name: customer_name
        description: "Customer name"
      - name: region
        description: "Customer region"
      - name: total_spent
        description: "Total amount spent by customer"

  - name: polars_analysis
    description: "Polars-based analysis of products by department"
    columns:
      - name: department
        description: "Product department"
      - name: product_count
        description: "Number of products in department"
      - name: total_department_value
        description: "Total value of all products in department"
      - name: avg_price
        description: "Average product price in department"
